name: fuzz

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          docker --version
          docker-compose --version
