name: fuzzing

on:
  push:
  workflow_dispatch:

jobs:
  fuzzing:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: setup webapp
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose ps -a

      - name: setup fuzzing scenario
        run: |
          cd fuzz
          npm i
          ./node_modules/typescript/bin/tsc scenario.ts
          file scenario.js

      - name: wait for mysql
        run: sleep 20

      - name: SHFZ setup
        uses: shfz/shfz-actions-setup@v0.0.1
        with:
          version: "0.0.2"

      - name: run fuzzing
        run: ./shfz run -f fuzz/scenario.js -n 100

      - name: export fuzzing report
        run: >
          curl
          -F "hash=${{ github.sha }}"
          -F "repo=${{ github.repository }}"
          -F "id=${{ github.run_id }}"
          -F "job=${{ github.job }}"
          -F "number=${{ github.run_number }}"
          -F "path=/app"
          http://localhost:53653/report > report.md
      - name: create issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: shfz result
          content-filepath: ./report.md
          labels: |
            shfz

      - name: export fuzzing data
        run: curl http://localhost:53653/data > result.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result.json
          path: ./result.json

      - name: export application log
        run: docker logs demo-webapp_app_1 > app.log
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.log
          path: ./app.log
